# Generated by Django 5.2.7 on 2025-10-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('base_datos_id', models.IntegerField()),
                ('campaña_id', models.IntegerField()),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('otros_datos', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'indexes': [models.Index(fields=['base_datos_id', 'campaña_id'], name='cliente_base_da_b8511b_idx'), models.Index(fields=['telefono'], name='cliente_telefon_12b836_idx')],
            },
        ),
    ]
