# Generated by Django 5.2.7 on 2025-10-12 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='centro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanas', to='users.centro', verbose_name='Centro'),
        ),
        migrations.AddField(
            model_name='campana',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campanas_estado', to='users.tiposparametros', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='campana',
            name='jefe_campana',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanas_a_cargo', to=settings.AUTH_USER_MODEL, verbose_name='Jefe de Campaña'),
        ),
        migrations.AddField(
            model_name='basedatoscargada',
            name='campana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bases_datos', to='campaigns.campana'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='base_datos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='campaigns.basedatoscargada'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='campana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='campaigns.campana'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='campana_id',
            field=models.ForeignKey(blank=True, db_column='campana_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campanas', to='campaigns.campana'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='campana',
            field=models.ForeignKey(blank=True, db_column='campania_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='campaigns.campana'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='coordinador',
            field=models.ForeignKey(blank=True, db_column='coordinador_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_coordinados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipoagentedetalle',
            name='agente_id',
            field=models.ForeignKey(db_column='agente_id', on_delete=django.db.models.deletion.CASCADE, related_name='equipos_detalle', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipoagentedetalle',
            name='equipo_id',
            field=models.ForeignKey(db_column='equipo_id', on_delete=django.db.models.deletion.CASCADE, related_name='agentes_detalle', to='campaigns.equipo'),
        ),
        migrations.AddField(
            model_name='productocampanadetalle',
            name='campana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_detalle', to='campaigns.campana'),
        ),
        migrations.AddField(
            model_name='productocampanadetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanas_detalle', to='campaigns.producto'),
        ),
        migrations.AddIndex(
            model_name='basedatoscargada',
            index=models.Index(fields=['campana', '-fecha_carga'], name='base_datos__campana_3768d7_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['base_datos_id', 'campana_id'], name='cliente_base_da_1933da_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['telefono'], name='cliente_telefon_12b836_idx'),
        ),
        migrations.AddIndex(
            model_name='equipoagentedetalle',
            index=models.Index(fields=['agente_id'], name='equipo_agen_agente__760262_idx'),
        ),
        migrations.AddIndex(
            model_name='equipoagentedetalle',
            index=models.Index(fields=['equipo_id'], name='equipo_agen_equipo__a9759d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='equipoagentedetalle',
            unique_together={('equipo_id', 'agente_id')},
        ),
        migrations.AddIndex(
            model_name='productocampanadetalle',
            index=models.Index(fields=['producto', 'campana'], name='producto_ca_product_9ddc17_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productocampanadetalle',
            unique_together={('producto', 'campana')},
        ),
    ]
