# Generated by Django 5.2.7 on 2025-10-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDatosCargada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campana_id', models.IntegerField()),
                ('nombre', models.CharField(max_length=150)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'base_datos_cargada',
            },
        ),
        migrations.RemoveIndex(
            model_name='cliente',
            name='cliente_base_da_b8511b_idx',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='campaña_id',
            new_name='campana_id',
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['base_datos_id', 'campana_id'], name='cliente_base_da_1933da_idx'),
        ),
    ]
