# Generated by Django 5.2.7 on 2025-10-09 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_basedatoscargada_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basedatoscargada',
            old_name='nombre',
            new_name='nombre_bd',
        ),
    ]
