# Generated by Django 4.2.7 on 2025-10-15 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("campaigns", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipo",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Indica si el equipo está activo",
                verbose_name="Activo",
            ),
        ),
        migrations.AddField(
            model_name="equipo",
            name="jefe_centro",
            field=models.ForeignKey(
                blank=True,
                db_column="jefe_centro_id",
                help_text="Jefe de centro responsable del equipo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipos_gestionados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="equipo",
            name="campana",
            field=models.ForeignKey(
                blank=True,
                db_column="campana_id",
                help_text="Campaña asignada al equipo",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="equipos",
                to="campaigns.campana",
            ),
        ),
        migrations.AlterField(
            model_name="equipo",
            name="coordinador",
            field=models.ForeignKey(
                blank=True,
                db_column="coordinador_id",
                help_text="Coordinador del equipo (opcional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipos_coordinados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="equipo",
            name="nombre",
            field=models.CharField(
                help_text="Nombre descriptivo del equipo",
                max_length=100,
                verbose_name="Nombre del Equipo",
            ),
        ),
        migrations.AlterField(
            model_name="equipoagentedetalle",
            name="agente_id",
            field=models.ForeignKey(
                db_column="agente_id",
                help_text="Agente asignado al equipo",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipos_detalle",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="equipoagentedetalle",
            name="equipo_id",
            field=models.ForeignKey(
                db_column="equipo_id",
                help_text="Equipo al que pertenece el agente",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agentes_detalle",
                to="campaigns.equipo",
            ),
        ),
        migrations.AddIndex(
            model_name="equipo",
            index=models.Index(
                fields=["jefe_centro", "is_active"], name="equipo_jefe_ce_3f9ad3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="equipo",
            index=models.Index(
                fields=["campana", "is_active"], name="equipo_campana_bb742a_idx"
            ),
        ),
    ]
