# Generated by Django 5.2.7 on 2025-10-16 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_equipo_is_active_equipo_jefe_centro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedatoscargada',
            name='fecha_hora_inicio_iteracion',
            field=models.DateTimeField(blank=True, help_text='Fecha/hora programada o real de inicio de iteración', null=True, verbose_name='Inicio de Iteración'),
        ),
        migrations.AddField(
            model_name='basedatoscargada',
            name='iteracion_activa',
            field=models.BooleanField(default=False, help_text='Indica si la base está actualmente en proceso de iteración', verbose_name='Iteración Activa'),
        ),
    ]
