# Generated by Django 5.2.7 on 2025-10-09 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_rename_nombre_basedatoscargada_nombre_bd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='base_datos_id',
        ),
        migrations.AddField(
            model_name='cliente',
            name='base_datos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='campaigns.basedatoscargada'),
        ),
    ]
