# Generated by Django 5.2.7 on 2025-10-12 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_remove_cliente_base_datos_id_cliente_base_datos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='basedatoscargada',
            options={'verbose_name': 'Base de Datos Cargada', 'verbose_name_plural': 'Bases de Datos Cargadas'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='base_datos',
            field=models.ForeignKey(blank=True, db_column='base_datos_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='campaigns.basedatoscargada'),
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='base_datos',
            new_name='base_datos_id',
        ),
        migrations.AlterField(
            model_name='basedatoscargada',
            name='campana_id',
            field=models.IntegerField(verbose_name='ID Campaña'),
        ),
        migrations.AlterField(
            model_name='basedatoscargada',
            name='fecha_carga',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga'),
        ),
        migrations.AlterField(
            model_name='basedatoscargada',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='basedatoscargada',
            name='nombre_bd',
            field=models.CharField(max_length=150, verbose_name='Nombre BD'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='campana_id',
            field=models.IntegerField(verbose_name='ID Campaña'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='otros_datos',
            field=models.JSONField(blank=True, null=True, verbose_name='Otros Datos'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('campana_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Campaña')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('jefe_campana', models.ForeignKey(blank=True, db_column='id_jefe_campana', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanas_dirigidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaña',
                'verbose_name_plural': 'Campañas',
                'db_table': 'campana',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('equipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Equipo')),
                ('campana', models.ForeignKey(blank=True, db_column='campania_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='campaigns.campana')),
                ('coordinador', models.ForeignKey(blank=True, db_column='coordinador_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_coordinados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'equipo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='IteracionCliente',
            fields=[
                ('contrato_id', models.AutoField(primary_key=True, serialize=False)),
                ('contrato_texto', models.TextField(blank=True, verbose_name='Texto del Contrato')),
                ('campana_id', models.ForeignKey(blank=True, db_column='campana_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campanas', to='campaigns.campana')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'db_table': 'contrato',
            },
        ),
        migrations.CreateModel(
            name='EquipoAgenteDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agente_id', models.ForeignKey(db_column='agente_id', on_delete=django.db.models.deletion.CASCADE, related_name='equipos_detalle', to=settings.AUTH_USER_MODEL)),
                ('equipo_id', models.ForeignKey(db_column='equipo_id', on_delete=django.db.models.deletion.CASCADE, related_name='agentes_detalle', to='campaigns.equipo')),
            ],
            options={
                'verbose_name': 'Detalle Equipo-Agente',
                'verbose_name_plural': 'Detalles Equipo-Agente',
                'db_table': 'equipo_agente_detalle',
                'indexes': [models.Index(fields=['agente_id'], name='equipo_agen_agente__760262_idx'), models.Index(fields=['equipo_id'], name='equipo_agen_equipo__a9759d_idx')],
                'unique_together': {('equipo_id', 'agente_id')},
            },
        ),
        migrations.CreateModel(
            name='ProductoCampanaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campana_id', models.ForeignKey(db_column='campana_id', on_delete=django.db.models.deletion.CASCADE, related_name='productos_detalle', to='campaigns.campana')),
                ('producto_id', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.CASCADE, related_name='campanas_detalle', to='campaigns.producto')),
            ],
            options={
                'verbose_name': 'Producto-Campaña Detalle',
                'verbose_name_plural': 'Productos-Campañas Detalle',
                'db_table': 'producto_campana_detalle',
                'unique_together': {('producto_id', 'campana_id')},
            },
        ),
    ]
