# Generated by Django 5.2.7 on 2025-10-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_basedatoscargada_fecha_hora_inicio_iteracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basedatoscargada',
            name='iteracion_activa',
            field=models.BooleanField(default=False, help_text='Indica si la base está actualmente en proceso de iteración', null=True, verbose_name='Iteración Activa'),
        ),
    ]
