# Generated by Django 4.2.7 on 2025-10-25 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("campaigns", "0005_alter_basedatoscargada_iteracion_activa"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="equipo",
            name="equipo_jefe_ce_3f9ad3_idx",
        ),
        migrations.RemoveField(
            model_name="equipo",
            name="jefe_centro",
        ),
        migrations.AlterField(
            model_name="equipo",
            name="coordinador",
            field=models.ForeignKey(
                blank=True,
                db_column="coordinador_id",
                help_text="Coordinador responsable del equipo",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipos_coordinados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="equipo",
            index=models.Index(
                fields=["coordinador", "is_active"], name="equipo_coordin_d02d17_idx"
            ),
        ),
    ]
