# Generated by Django 5.2.7 on 2025-11-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_remove_jefe_centro_add_coordinador_to_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='comision_porcentaje',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Porcentaje de comisión para ventas de esta campaña (ej: 15.00 = 15%)', max_digits=5, verbose_name='Porcentaje de Comisión'),
        ),
    ]
