# Generated by Django 5.2.7 on 2025-10-12 04:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('first_name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=150, verbose_name='Apellido')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('documento_id', models.CharField(help_text='Numero de documento de indentidad', max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Documento de Identidad')),
                ('foto_perfil', models.URLField(blank=True, help_text='URL de la foto de perfil del usuario', max_length=500, null=True, verbose_name='Foto de Perfil')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Centro')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('jefe_centro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centros_a_cargo', to=settings.AUTH_USER_MODEL, verbose_name='Jefe de Centro')),
            ],
            options={
                'verbose_name': 'Centro',
                'verbose_name_plural': 'Centros',
                'db_table': 'centro',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TiposParametros',
            fields=[
                ('parametros_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('valor', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo de Parámetro',
                'verbose_name_plural': 'Tipos de Parámetros',
                'db_table': 'tipos_parametros',
                'indexes': [models.Index(fields=['nombre'], name='tipos_param_nombre_534abb_idx')],
                'unique_together': {('nombre', 'valor')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.ForeignKey(blank=True, db_column='rol_id', help_text='Referencia al tipo de rol (ROL_USUARIO)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_rol', to='users.tiposparametros'),
        ),
        migrations.CreateModel(
            name='EstadoAgenteActual',
            fields=[
                ('agente_id', models.OneToOneField(db_column='agente_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='estado_actual', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tiempo', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tiempo')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado_id', models.ForeignKey(blank=True, db_column='estado_id', help_text='Estado actual del agente (ESTADO_AGENTE)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agentes_estado_actual', to='users.tiposparametros')),
            ],
            options={
                'verbose_name': 'Estado Actual del Agente',
                'verbose_name_plural': 'Estados Actuales de Agentes',
                'db_table': 'estado_agente_actual',
            },
        ),
        migrations.CreateModel(
            name='EstadoAgenteDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tiempo')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('cambios', models.TextField(blank=True, verbose_name='Cambios')),
                ('agente_id', models.ForeignKey(db_column='agente_id', on_delete=django.db.models.deletion.CASCADE, related_name='estados_detalle', to=settings.AUTH_USER_MODEL)),
                ('estado_id', models.ForeignKey(blank=True, db_column='estado_id', help_text='Estado del agente (ESTADO_AGENTE)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estados_agente', to='users.tiposparametros')),
            ],
            options={
                'verbose_name': 'Estado Agente Detalle',
                'verbose_name_plural': 'Estados Agente Detalle',
                'db_table': 'estado_agente_detalle',
                'ordering': ['-fecha', '-tiempo'],
                'indexes': [models.Index(fields=['agente_id', 'fecha'], name='estado_agen_agente__34be79_idx'), models.Index(fields=['estado_id', 'fecha'], name='estado_agen_estado__e25a70_idx'), models.Index(fields=['agente_id', '-tiempo'], name='estado_agen_agente__b8a309_idx')],
            },
        ),
    ]
