# Generated by Django 5.2.7 on 2025-10-12 05:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoagentedetalle',
            name='cambios',
            field=models.TextField(blank=True, default='', help_text='Historial de cambios  "HH:MM:SS - nombre_usuario, ..."', verbose_name='Cambios'),
        ),
        migrations.AlterField(
            model_name='estadoagentedetalle',
            name='estado_id',
            field=models.ForeignKey(blank=True, db_column='estado_id', help_text='Estado del agente (ESTADO_AGENTE)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estados_agente', to='users.tiposparametros'),
        ),
        migrations.AlterField(
            model_name='estadoagentedetalle',
            name='fecha',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='estadoagentedetalle',
            name='tiempo',
            field=models.CharField(default='00:00:00', help_text='Tiempo total acumulado en el dia HH:MM:SS', max_length=8),
        ),
    ]
