# Generated by Django 4.2.7 on 2025-10-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="documento_id",
            field=models.CharField(
                blank=True,
                help_text="Cédula, DNI, Pasaporte u otro documento de identificación",
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Documento de Identidad",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="foto_perfil",
            field=models.URLField(
                blank=True,
                help_text="URL de la foto de perfil del usuario",
                max_length=500,
                null=True,
                verbose_name="Foto de Perfil",
            ),
        ),
    ]
