# Generated by Django 4.2.7 on 2025-10-08 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_documento_id_user_foto_perfil"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre del Equipo"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Supervisor o administrador del equipo",
                        limit_choices_to={"role": "ADMIN"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipos_supervisados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipo",
                "verbose_name_plural": "Equipos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="TiposParametros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("ESTADO_AGENTE", "Estado de Agente"),
                            ("ESTADO_LLAMADA", "Estado de Llamada"),
                            ("TIPO_LLAMADA", "Tipo de Llamada"),
                            ("MOTIVO_RECHAZO", "Motivo de Rechazo"),
                        ],
                        help_text="Categoría del parámetro",
                        max_length=50,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código único del parámetro dentro de su categoría",
                        max_length=50,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre descriptivo del parámetro",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Descripción detallada del parámetro",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Color asociado (ej: #00FF00 para verde)",
                        max_length=20,
                        verbose_name="Color",
                    ),
                ),
                (
                    "icono",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del icono (ej: check, clock, phone)",
                        max_length=50,
                        verbose_name="Icono",
                    ),
                ),
                (
                    "orden",
                    models.IntegerField(
                        default=0,
                        help_text="Orden de visualización",
                        verbose_name="Orden",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Parámetro",
                "verbose_name_plural": "Tipos de Parámetros",
                "ordering": ["categoria", "orden", "nombre"],
                "indexes": [
                    models.Index(
                        fields=["categoria", "codigo"],
                        name="users_tipos_categor_414016_idx",
                    ),
                    models.Index(
                        fields=["categoria", "activo"],
                        name="users_tipos_categor_bd933f_idx",
                    ),
                ],
                "unique_together": {("categoria", "codigo")},
            },
        ),
        migrations.CreateModel(
            name="EstadoAgenteDetalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("DISPONIBLE", "Disponible"),
                            ("OCUPADO", "Ocupado"),
                            ("DESCONECTADO", "Desconectado"),
                            ("EN_PAUSA", "En Pausa"),
                            ("EN_LLAMADA", "En Llamada"),
                            ("POSTCALL", "Post-Llamada"),
                        ],
                        help_text="Estado actual del agente",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Fecha del cambio de estado",
                        verbose_name="Fecha",
                    ),
                ),
                (
                    "hora_inicio",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Momento exacto del cambio de estado",
                        verbose_name="Hora de Inicio",
                    ),
                ),
                (
                    "hora_fin",
                    models.DateTimeField(
                        blank=True,
                        help_text="Momento en que finaliza este estado",
                        null=True,
                        verbose_name="Hora de Fin",
                    ),
                ),
                (
                    "duracion_segundos",
                    models.IntegerField(
                        blank=True,
                        help_text="Duración total en este estado",
                        null=True,
                        verbose_name="Duración (segundos)",
                    ),
                ),
                (
                    "comentarios",
                    models.TextField(
                        blank=True,
                        help_text="Comentarios opcionales sobre el cambio de estado",
                        verbose_name="Comentarios",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP desde donde se realizó el cambio",
                        null=True,
                        verbose_name="Dirección IP",
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        help_text="Navegador/dispositivo usado",
                        max_length=255,
                        verbose_name="User Agent",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "agente",
                    models.ForeignKey(
                        limit_choices_to={"role": "AGENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_estados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "estado_parametro",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"categoria": "ESTADO_AGENTE"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estados_agente",
                        to="users.tiposparametros",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estado de Agente",
                "verbose_name_plural": "Historial de Estados de Agentes",
                "ordering": ["-hora_inicio"],
            },
        ),
        migrations.CreateModel(
            name="EstadoAgenteActual",
            fields=[
                (
                    "agente",
                    models.OneToOneField(
                        limit_choices_to={"role": "AGENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="estado_actual",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("DISPONIBLE", "Disponible"),
                            ("OCUPADO", "Ocupado"),
                            ("DESCONECTADO", "Desconectado"),
                            ("EN_PAUSA", "En Pausa"),
                            ("EN_LLAMADA", "En Llamada"),
                            ("POSTCALL", "Post-Llamada"),
                        ],
                        default="DESCONECTADO",
                        max_length=20,
                        verbose_name="Estado Actual",
                    ),
                ),
                (
                    "ultima_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "acepta_llamadas",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si el agente puede recibir llamadas",
                        verbose_name="Acepta Llamadas",
                    ),
                ),
                (
                    "tiene_audio",
                    models.BooleanField(
                        default=False,
                        help_text="Audio/micrófono configurado correctamente",
                        verbose_name="Tiene Audio",
                    ),
                ),
                (
                    "conexion_activa",
                    models.BooleanField(
                        default=False,
                        help_text="Tiene conexión a internet estable",
                        verbose_name="Conexión Activa",
                    ),
                ),
                (
                    "detalle",
                    models.ForeignKey(
                        blank=True,
                        help_text="Referencia al registro detallado actual",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="users.estadoagentedetalle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estado Actual de Agente",
                "verbose_name_plural": "Estados Actuales de Agentes",
            },
        ),
        migrations.CreateModel(
            name="EquipoAgenteDetalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_asignacion",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Asignación",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "agente",
                    models.ForeignKey(
                        limit_choices_to={"role": "AGENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipos_detalle",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agentes_detalle",
                        to="users.equipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle Equipo-Agente",
                "verbose_name_plural": "Detalles Equipo-Agente",
                "ordering": ["-fecha_asignacion"],
            },
        ),
        migrations.AddIndex(
            model_name="estadoagentedetalle",
            index=models.Index(
                fields=["agente", "-hora_inicio"], name="users_estad_agente__fedf70_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="estadoagentedetalle",
            index=models.Index(
                fields=["agente", "estado"], name="users_estad_agente__e93d2d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="estadoagentedetalle",
            index=models.Index(
                fields=["fecha", "estado"], name="users_estad_fecha_22fdf6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="equipoagentedetalle",
            index=models.Index(
                fields=["agente", "activo"], name="users_equip_agente__30b64e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="equipoagentedetalle",
            index=models.Index(
                fields=["equipo", "activo"], name="users_equip_equipo__4c8167_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="equipoagentedetalle",
            unique_together={("equipo", "agente")},
        ),
    ]
