# Generated by Django 5.2.7 on 2025-10-12 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_estadoagentedetalle_cambios_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='estadoagentedetalle',
            name='estado_agen_agente__b8a309_idx',
        ),
        migrations.AlterUniqueTogether(
            name='estadoagentedetalle',
            unique_together={('agente_id', 'estado_id', 'fecha')},
        ),
    ]
