# Generated by Django 5.2.7 on 2025-10-09 03:44

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_documento_id_user_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposParametros',
            fields=[
                ('parametros_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('valor', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo de Parámetro',
                'verbose_name_plural': 'Tipos de Parámetros',
                'db_table': 'tipos_parametros',
                'unique_together': {('nombre', 'valor')},
            },
        ),
        migrations.CreateModel(
            name='EstadoActualAgente',
            fields=[
                ('agente', models.OneToOneField(db_column='documento_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='estado_actual', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(db_column='estado_id', limit_choices_to={'nombre': 'ESTADO_AGENTE'}, on_delete=django.db.models.deletion.PROTECT, to='users.tiposparametros')),
            ],
            options={
                'verbose_name': 'Estado Actual Agente',
                'verbose_name_plural': 'Estados Actuales Agente',
                'db_table': 'estado_actual_agente',
            },
        ),
        migrations.CreateModel(
            name='EstadoAgenteDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.CharField(default='00:00:00', help_text='Tiempo total acumulado en el día (HH:MM:SS)', max_length=8)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('cambios', models.TextField(blank=True, default='', help_text="Historial: 'HH:MM:SS - usuario, HH:MM:SS - usuario, ...'")),
                ('agente', models.ForeignKey(db_column='agente_id', on_delete=django.db.models.deletion.CASCADE, related_name='estados_detalle', to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(db_column='estado_id', limit_choices_to={'nombre': 'ESTADO_AGENTE'}, on_delete=django.db.models.deletion.PROTECT, related_name='estados_agente_detalle', to='users.tiposparametros')),
            ],
            options={
                'verbose_name': 'Estado Agente Detalle',
                'verbose_name_plural': 'Estados Agente Detalle',
                'db_table': 'estado_agente_detalle',
                'indexes': [models.Index(fields=['agente', 'fecha'], name='estado_agen_agente__34be79_idx'), models.Index(fields=['estado', 'fecha'], name='estado_agen_estado__e25a70_idx')],
                'unique_together': {('agente', 'estado', 'fecha')},
            },
        ),
    ]
