# Generated by Django 4.2.7 on 2025-10-10 02:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_documento_id_user_foto_perfil"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre del Equipo"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Supervisor o administrador del equipo",
                        limit_choices_to={"role": "ADMIN"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipos_supervisados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipo",
                "verbose_name_plural": "Equipos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="TiposParametros",
            fields=[
                ("parametros_id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=50)),
                ("valor", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Tipo de Parámetro",
                "verbose_name_plural": "Tipos de Parámetros",
                "db_table": "tipos_parametros",
                "unique_together": {("nombre", "valor")},
            },
        ),
        migrations.CreateModel(
            name="EstadoAgenteActual",
            fields=[
                (
                    "agente",
                    models.OneToOneField(
                        limit_choices_to={"role": "AGENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="estado_actual",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("DISPONIBLE", "Disponible"),
                            ("EN_LLAMADA", "En Llamada"),
                            ("POSTCALL", "Post Llamada"),
                            ("BREAK", "Break"),
                            ("ALMUERZO", "Almuerzo"),
                            ("CAPACITACION", "Capacitación"),
                            ("REUNION", "Reunión"),
                            ("AUSENTE", "Ausente"),
                            ("DESCONECTADO", "Desconectado"),
                        ],
                        default="DESCONECTADO",
                        max_length=20,
                        verbose_name="Estado Actual",
                    ),
                ),
                (
                    "hora_inicio_estado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Hora en que entró al estado actual",
                        verbose_name="Hora Inicio Estado",
                    ),
                ),
                (
                    "ultima_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "acepta_llamadas",
                    models.BooleanField(
                        default=False,
                        help_text="Si el agente está disponible para recibir llamadas",
                        verbose_name="Acepta Llamadas",
                    ),
                ),
                (
                    "conexion_activa",
                    models.BooleanField(
                        default=False,
                        help_text="Si el agente está conectado al sistema",
                        verbose_name="Conexión Activa",
                    ),
                ),
                (
                    "tiene_audio",
                    models.BooleanField(
                        default=False,
                        help_text="Si el agente tiene audio/micrófono activo",
                        verbose_name="Tiene Audio",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dirección IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        help_text="Información del navegador",
                        max_length=500,
                        verbose_name="User Agent",
                    ),
                ),
                (
                    "comentarios",
                    models.TextField(
                        blank=True,
                        help_text="Motivo del estado actual",
                        verbose_name="Comentarios",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Fecha de creación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Estado Actual del Agente",
                "verbose_name_plural": "Estados Actuales de Agentes",
                "db_table": "estado_agente_actual",
                "indexes": [
                    models.Index(
                        fields=["estado", "acepta_llamadas"],
                        name="estado_agen_estado_c55308_idx",
                    ),
                    models.Index(
                        fields=["conexion_activa"],
                        name="estado_agen_conexio_52c1f0_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EstadoAgenteDetalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        help_text="Estado del agente durante este período",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(default=datetime.date.today, verbose_name="Fecha"),
                ),
                (
                    "hora_inicio",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Hora Inicio"
                    ),
                ),
                (
                    "hora_fin",
                    models.DateTimeField(
                        blank=True,
                        help_text="Hora en que salió del estado (NULL = aún activo)",
                        null=True,
                        verbose_name="Hora Fin",
                    ),
                ),
                (
                    "duracion_segundos",
                    models.IntegerField(
                        blank=True,
                        help_text="Duración calculada automáticamente",
                        null=True,
                        verbose_name="Duración en Segundos",
                    ),
                ),
                (
                    "comentarios",
                    models.TextField(
                        blank=True,
                        help_text="Motivo o notas sobre el cambio de estado",
                        verbose_name="Comentarios",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dirección IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="User Agent"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "agente",
                    models.ForeignKey(
                        limit_choices_to={"role": "AGENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estados_detalle",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Estado Agente Detalle",
                "verbose_name_plural": "Estados Agente Detalle",
                "db_table": "estado_agente_detalle",
                "ordering": ["-fecha", "-hora_inicio"],
                "indexes": [
                    models.Index(
                        fields=["agente", "fecha"],
                        name="estado_agen_agente__34be79_idx",
                    ),
                    models.Index(
                        fields=["estado", "fecha"], name="estado_agen_estado_1bd50e_idx"
                    ),
                    models.Index(
                        fields=["agente", "-hora_inicio"],
                        name="estado_agen_agente__f0c95b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EquipoAgenteDetalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_asignacion",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Asignación",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "agente",
                    models.ForeignKey(
                        limit_choices_to={"role": "AGENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipos_detalle",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agentes_detalle",
                        to="users.equipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle Equipo-Agente",
                "verbose_name_plural": "Detalles Equipo-Agente",
                "ordering": ["-fecha_asignacion"],
                "indexes": [
                    models.Index(
                        fields=["agente", "activo"],
                        name="users_equip_agente__30b64e_idx",
                    ),
                    models.Index(
                        fields=["equipo", "activo"],
                        name="users_equip_equipo__4c8167_idx",
                    ),
                ],
                "unique_together": {("equipo", "agente")},
            },
        ),
    ]
