# Generated by Django 5.2.7 on 2025-10-12 01:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_equipo_tiposparametros_estadoagenteactual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('centro_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Centro')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Centro',
                'verbose_name_plural': 'Centros',
                'db_table': 'centro',
                'ordering': ['nombre'],
            },
        ),

        # --- Ajustes en otros modelos existentes ---

        migrations.AlterModelOptions(
            name='estadoagentedetalle',
            options={
                'ordering': ['-fecha', '-tiempo'],
                'verbose_name': 'Estado Agente Detalle',
                'verbose_name_plural': 'Estados Agente Detalle',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),

        # --- Campos nuevos en EstadoAgenteActual ---
        migrations.AddField(
            model_name='estadoagenteactual',
            name='agente_id',
            field=models.OneToOneField(
                db_column='agente_id',
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name='estado_actual',
                serialize=False,
                to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estadoagenteactual',
            name='estado_id',
            field=models.ForeignKey(
                blank=True,
                db_column='estado_id',
                help_text='Estado actual del agente (ESTADO_AGENTE)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='agentes_estado_actual',
                to='users.tiposparametros',
            ),
        ),
        migrations.AddField(
            model_name='estadoagenteactual',
            name='tiempo',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tiempo'),
        ),

        # --- Campos nuevos en EstadoAgenteDetalle ---
        migrations.AddField(
            model_name='estadoagentedetalle',
            name='agente_id',
            field=models.ForeignKey(
                db_column='agente_id',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='estados_detalle',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='estadoagentedetalle',
            name='cambios',
            field=models.TextField(blank=True, verbose_name='Cambios'),
        ),
        migrations.AddField(
            model_name='estadoagentedetalle',
            name='estado_id',
            field=models.ForeignKey(
                blank=True,
                db_column='estado_id',
                help_text='Estado del agente (ESTADO_AGENTE)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='estados_agente',
                to='users.tiposparametros',
            ),
        ),
        migrations.AddField(
            model_name='estadoagentedetalle',
            name='tiempo',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tiempo'),
        ),
        migrations.AlterField(
            model_name='estadoagentedetalle',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),

        # --- Campos nuevos en User ---
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.ForeignKey(
                blank=True,
                db_column='rol_id',
                help_text='Referencia al tipo de rol (ROL_USUARIO)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='usuarios_rol',
                to='users.tiposparametros',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='documento_id',
            field=models.CharField(
                help_text='Numero de documento de indentidad',
                max_length=50,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name='Documento de Identidad',
            ),
        ),

        # --- Índices útiles ---
        migrations.AddIndex(
            model_name='estadoagentedetalle',
            index=models.Index(fields=['agente_id', 'fecha'], name='estado_agen_agente__34be79_idx'),
        ),
        migrations.AddIndex(
            model_name='estadoagentedetalle',
            index=models.Index(fields=['estado_id', 'fecha'], name='estado_agen_estado__e25a70_idx'),
        ),
        migrations.AddIndex(
            model_name='estadoagentedetalle',
            index=models.Index(fields=['agente_id', '-tiempo'], name='estado_agen_agente__b8a309_idx'),
        ),
        migrations.AddIndex(
            model_name='tiposparametros',
            index=models.Index(fields=['nombre'], name='tipos_param_nombre_534abb_idx'),
        ),

        # --- Relación jefe_centro en Centro ---
        migrations.AddField(
            model_name='centro',
            name='jefe_centro',
            field=models.ForeignKey(
                blank=True,
                db_column='jefe_centro_id',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='centros_dirigidos',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
