# Generated by Django 5.2.7 on 2025-10-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_estadoagentedetalle_estado_agen_agente__b8a309_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='documento_id',
            field=models.IntegerField(help_text='Numero de documento de indentidad', primary_key=True, serialize=False, unique=True, verbose_name='Documento de Identidad'),
        ),
    ]
