# Generated by Django 5.2.7 on 2025-10-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_documento_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='documento_id',
            field=models.CharField(help_text='Numero de documento de indentidad', max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Documento de Identidad'),
        ),
    ]
