# Generated by Django 5.2.7 on 2025-10-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_equipo_supervisor_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='estadoagentedetalle',
            index=models.Index(fields=['agente_id', 'fecha'], name='estado_agen_agente__34be79_idx'),
        ),
    ]
