# Generated by Django 5.2.7 on 2025-11-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_documento_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estadoagentedetalle",
            name="tiempo",
            field=models.CharField(
                default="00:00:00",
                help_text="Tiempo total acumulado en el dia HH:MM:SS",
                max_length=15,
            ),
        ),
    ]
