# Generated by Django 4.2.7 on 2025-11-26 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_estadoagentedetalle_tiempo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="foto_perfil",
            field=models.TextField(
                blank=True,
                help_text="Foto de perfil del usuario en formato base64 (data:image/...)",
                null=True,
                verbose_name="Foto de Perfil",
            ),
        ),
    ]
