# Generated by Django 4.2.7 on 2025-10-30 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        help_text="Token único y seguro para resetear contraseña",
                        max_length=64,
                        unique=True,
                        verbose_name="Token",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Token expira después de 1 hora",
                        verbose_name="Fecha de expiración",
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False,
                        help_text="Marca si el token ya fue utilizado",
                        verbose_name="Usado",
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Momento en que se usó el token",
                        null=True,
                        verbose_name="Fecha de uso",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP desde donde se solicitó el reseteo",
                        null=True,
                        verbose_name="Dirección IP",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token de Recuperación de Contraseña",
                "verbose_name_plural": "Tokens de Recuperación de Contraseña",
                "db_table": "password_reset_token",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["token", "is_used"], name="password_re_token_1b4414_idx"
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="password_re_user_id_f9e5cd_idx",
                    ),
                ],
            },
        ),
    ]
