# Generated by Django 5.2.7 on 2025-10-12 04:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campos_json', models.JSONField(default=dict, help_text='Estructura JSON con los campos y valores del formulario', verbose_name='Campos del Formulario')),
                ('completado', models.BooleanField(default=False, verbose_name='Completado')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Formulario de Llamada',
                'verbose_name_plural': 'Formularios de Llamadas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IteracionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intento', models.IntegerField(default=1, verbose_name='Número de Intento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Iteración de Cliente',
                'verbose_name_plural': 'Iteraciones de Clientes',
                'db_table': 'iteracion_cliente',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Llamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora de Inicio')),
                ('fecha_hora_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Fin')),
                ('duracion', models.IntegerField(blank=True, null=True, verbose_name='Duración (segundos)')),
                ('transcipcion', models.TextField(blank=True, verbose_name='Transcripción')),
                ('grabacion_url', models.URLField(blank=True, max_length=500, verbose_name='URL de Grabación')),
                ('twilio_call_sid', models.CharField(blank=True, help_text='ID único de la llamada en Twilio', max_length=100, verbose_name='Twilio Call SID')),
                ('twilio_status', models.CharField(blank=True, help_text='Estado de la llamada en Twilio', max_length=50, verbose_name='Estado Twilio')),
                ('twilio_recording_sid', models.CharField(blank=True, help_text='ID de la grabación en Twilio', max_length=100, verbose_name='Twilio Recording SID')),
                ('twilio_recording_url', models.URLField(blank=True, help_text='URL de la grabación en Twilio', max_length=500, verbose_name='URL Grabación Twilio')),
                ('telefono_origen', models.CharField(max_length=20, verbose_name='Teléfono de Origen')),
                ('telefono_destino', models.CharField(max_length=20, verbose_name='Teléfono de Destino')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Llamada',
                'verbose_name_plural': 'Llamadas',
                'db_table': 'llamada',
                'ordering': ['-fecha_hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('venta_id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'venta',
            },
        ),
    ]
