# Generated by Django 4.2.7 on 2025-10-08 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campana",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre de la Campaña"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("VENTAS", "Ventas"),
                            ("COBRANZAS", "Cobranzas"),
                            ("ENCUESTAS", "Encuestas"),
                            ("SOPORTE", "Soporte"),
                            ("MARKETING", "Marketing"),
                        ],
                        default="VENTAS",
                        max_length=20,
                        verbose_name="Tipo de Campaña",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Inicio",
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Fin"
                    ),
                ),
                ("activa", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "objetivo_llamadas",
                    models.IntegerField(
                        blank=True,
                        help_text="Meta de llamadas para esta campaña",
                        null=True,
                        verbose_name="Objetivo de Llamadas",
                    ),
                ),
                (
                    "objetivo_ventas",
                    models.IntegerField(
                        blank=True,
                        help_text="Meta de ventas/conversiones",
                        null=True,
                        verbose_name="Objetivo de Ventas",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaña",
                "verbose_name_plural": "Campañas",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150, verbose_name="Nombre")),
                (
                    "apellido",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Apellido"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        help_text="Número de teléfono principal",
                        max_length=20,
                        verbose_name="Teléfono",
                    ),
                ),
                (
                    "telefono_alternativo",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono Alternativo"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Correo Electrónico"
                    ),
                ),
                (
                    "documento_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Documento de Identidad",
                    ),
                ),
                ("direccion", models.TextField(blank=True, verbose_name="Dirección")),
                (
                    "ciudad",
                    models.CharField(blank=True, max_length=100, verbose_name="Ciudad"),
                ),
                (
                    "pais",
                    models.CharField(
                        blank=True,
                        default="Colombia",
                        max_length=100,
                        verbose_name="País",
                    ),
                ),
                (
                    "notas",
                    models.TextField(
                        blank=True,
                        help_text="Notas adicionales sobre el cliente",
                        verbose_name="Notas",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["apellido", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Llamada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "llamada_sid",
                    models.CharField(
                        blank=True,
                        help_text="ID único de Twilio o sistema telefónico",
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="SID de Llamada",
                    ),
                ),
                (
                    "tipo_llamada",
                    models.CharField(
                        choices=[("ENTRANTE", "Entrante"), ("SALIENTE", "Saliente")],
                        default="ENTRANTE",
                        max_length=20,
                        verbose_name="Tipo de Llamada",
                    ),
                ),
                (
                    "telefono_origen",
                    models.CharField(
                        help_text="Número que llama",
                        max_length=20,
                        verbose_name="Teléfono de Origen",
                    ),
                ),
                (
                    "telefono_destino",
                    models.CharField(
                        help_text="Número al que se llama",
                        max_length=20,
                        verbose_name="Teléfono de Destino",
                    ),
                ),
                (
                    "estado_llamada",
                    models.CharField(
                        choices=[
                            ("TIMBRADO", "Timbrado"),
                            ("EN_CURSO", "En Curso"),
                            ("COMPLETADA", "Completada"),
                            ("NO_CONTESTADA", "No Contestada"),
                            ("RECHAZADA", "Rechazada"),
                            ("TRANSFERIDA", "Transferida"),
                            ("COLGADA", "Colgada"),
                        ],
                        default="TIMBRADO",
                        max_length=20,
                        verbose_name="Estado de Llamada",
                    ),
                ),
                (
                    "estado_recibida",
                    models.BooleanField(
                        default=False,
                        help_text="Si el agente aceptó la llamada",
                        verbose_name="Recibida",
                    ),
                ),
                (
                    "hora_inicio_timbrado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Momento en que empieza a sonar",
                        verbose_name="Hora Inicio Timbrado",
                    ),
                ),
                (
                    "hora_inicio_llamada",
                    models.DateTimeField(
                        blank=True,
                        help_text="Momento en que el agente contesta",
                        null=True,
                        verbose_name="Hora Inicio Llamada",
                    ),
                ),
                (
                    "hora_fin_llamada",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Hora Fin Llamada"
                    ),
                ),
                (
                    "duracion_timbrado_segundos",
                    models.IntegerField(
                        blank=True,
                        help_text="Tiempo que sonó antes de ser atendida o rechazada",
                        null=True,
                        verbose_name="Duración Timbrado (seg)",
                    ),
                ),
                (
                    "duracion_llamada_segundos",
                    models.IntegerField(
                        blank=True,
                        help_text="Duración total de la conversación",
                        null=True,
                        verbose_name="Duración Llamada (seg)",
                    ),
                ),
                (
                    "grabacion_url",
                    models.URLField(
                        blank=True,
                        help_text="URL de la grabación en Twilio o servidor",
                        max_length=500,
                        verbose_name="URL de Grabación",
                    ),
                ),
                (
                    "grabacion_duracion",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Duración Grabación (seg)"
                    ),
                ),
                (
                    "motivo_rechazo",
                    models.CharField(
                        blank=True,
                        help_text="Razón por la que se rechazó la llamada",
                        max_length=100,
                        verbose_name="Motivo de Rechazo",
                    ),
                ),
                (
                    "notas",
                    models.TextField(
                        blank=True,
                        help_text="Notas del agente sobre la llamada",
                        verbose_name="Notas",
                    ),
                ),
                (
                    "requiere_seguimiento",
                    models.BooleanField(
                        default=False, verbose_name="Requiere Seguimiento"
                    ),
                ),
                (
                    "intentos_redireccion",
                    models.IntegerField(
                        default=0,
                        help_text="Número de veces que se redirigió a otro agente",
                        verbose_name="Intentos de Redirección",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dirección IP"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Datos adicionales de la llamada",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "agente",
                    models.ForeignKey(
                        limit_choices_to={"role": "AGENT"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="llamadas_atendidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "agente_anterior",
                    models.ForeignKey(
                        blank=True,
                        help_text="Agente que transfirió esta llamada",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="llamadas_transferidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "campana",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="llamadas",
                        to="calls.campana",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="llamadas",
                        to="calls.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Llamada",
                "verbose_name_plural": "Llamadas",
                "ordering": ["-hora_inicio_timbrado"],
            },
        ),
        migrations.CreateModel(
            name="FormularioLlamada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "campos_json",
                    models.JSONField(
                        default=dict,
                        help_text="Estructura JSON con los campos y valores del formulario",
                        verbose_name="Campos del Formulario",
                    ),
                ),
                (
                    "completado",
                    models.BooleanField(default=False, verbose_name="Completado"),
                ),
                (
                    "fecha_completado",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Completado"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "agente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formularios_completados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "llamada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formularios",
                        to="calls.llamada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Formulario de Llamada",
                "verbose_name_plural": "Formularios de Llamadas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(
                fields=["telefono"], name="calls_clien_telefon_35faf7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(
                fields=["documento_id"], name="calls_clien_documen_0e94be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(fields=["email"], name="calls_clien_email_9f02e4_idx"),
        ),
        migrations.AddIndex(
            model_name="llamada",
            index=models.Index(
                fields=["agente", "-hora_inicio_timbrado"],
                name="calls_llama_agente__b50ec5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="llamada",
            index=models.Index(
                fields=["cliente", "-hora_inicio_timbrado"],
                name="calls_llama_cliente_4f9b18_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="llamada",
            index=models.Index(
                fields=["estado_llamada", "-hora_inicio_timbrado"],
                name="calls_llama_estado__7be6c5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="llamada",
            index=models.Index(
                fields=["llamada_sid"], name="calls_llama_llamada_99841c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="llamada",
            index=models.Index(
                fields=["telefono_origen"], name="calls_llama_telefon_a3221e_idx"
            ),
        ),
    ]
