# Generated by Django 5.2.7 on 2025-10-12 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calls', '0001_initial'),
        ('campaigns', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formularioventa',
            name='agente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios_completados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='iteracioncliente',
            name='campana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iteraciones', to='campaigns.campana'),
        ),
        migrations.AddField(
            model_name='iteracioncliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iteraciones', to='campaigns.cliente'),
        ),
        migrations.AddField(
            model_name='iteracioncliente',
            name='estado_iteracion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='iteraciones_estado', to='users.tiposparametros'),
        ),
        migrations.AddField(
            model_name='llamada',
            name='agente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llamadas_atendidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='llamada',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llamadas', to='campaigns.cliente'),
        ),
        migrations.AddField(
            model_name='llamada',
            name='estado_llamada',
            field=models.ForeignKey(help_text='Estado: contestada, no contestada', on_delete=django.db.models.deletion.PROTECT, related_name='llamadas_estado_llamada', to='users.tiposparametros'),
        ),
        migrations.AddField(
            model_name='llamada',
            name='estado_reportada',
            field=models.ForeignKey(help_text='Estado: reportada, no reportada', on_delete=django.db.models.deletion.PROTECT, related_name='llamadas_estado_reportada', to='users.tiposparametros'),
        ),
        migrations.AddField(
            model_name='llamada',
            name='estado_venta',
            field=models.ForeignKey(help_text='Estado: venta, no venta', on_delete=django.db.models.deletion.PROTECT, related_name='llamadas_estado_venta', to='users.tiposparametros'),
        ),
        migrations.AddField(
            model_name='formularioventa',
            name='llamada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios', to='calls.llamada'),
        ),
        migrations.AddField(
            model_name='venta',
            name='campana_id',
            field=models.ForeignKey(db_column='campana_id', on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='campaigns.campana'),
        ),
        migrations.AddField(
            model_name='llamada',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llamadas', to='calls.venta'),
        ),
        migrations.AddIndex(
            model_name='iteracioncliente',
            index=models.Index(fields=['campana', 'cliente'], name='iteracion_c_campana_f27800_idx'),
        ),
        migrations.AddIndex(
            model_name='iteracioncliente',
            index=models.Index(fields=['cliente', '-created_at'], name='iteracion_c_cliente_295ed5_idx'),
        ),
        migrations.AddIndex(
            model_name='llamada',
            index=models.Index(fields=['agente', '-fecha_hora_inicio'], name='llamada_agente__1be2e6_idx'),
        ),
        migrations.AddIndex(
            model_name='llamada',
            index=models.Index(fields=['cliente', '-fecha_hora_inicio'], name='llamada_cliente_c30a0c_idx'),
        ),
        migrations.AddIndex(
            model_name='llamada',
            index=models.Index(fields=['estado_llamada'], name='llamada_estado__0d7346_idx'),
        ),
        migrations.AddIndex(
            model_name='llamada',
            index=models.Index(fields=['telefono_origen'], name='llamada_telefon_29a689_idx'),
        ),
    ]
