# Generated by Django 4.2.7 on 2025-10-09 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="llamada",
            name="twilio_call_sid",
            field=models.CharField(
                blank=True,
                help_text="ID único de la llamada en Twilio",
                max_length=100,
                verbose_name="Twilio Call SID",
            ),
        ),
        migrations.AddField(
            model_name="llamada",
            name="twilio_recording_sid",
            field=models.CharField(
                blank=True,
                help_text="ID de la grabación en Twilio",
                max_length=100,
                verbose_name="Twilio Recording SID",
            ),
        ),
        migrations.AddField(
            model_name="llamada",
            name="twilio_recording_url",
            field=models.URLField(
                blank=True,
                help_text="URL de la grabación en los servidores de Twilio",
                max_length=500,
                verbose_name="URL Grabación Twilio",
            ),
        ),
        migrations.AddField(
            model_name="llamada",
            name="twilio_status",
            field=models.CharField(
                blank=True,
                help_text="Estado de la llamada en Twilio (ringing, in-progress, completed, etc.)",
                max_length=50,
                verbose_name="Estado Twilio",
            ),
        ),
    ]
