# Generated by Django 5.2.7 on 2025-10-28 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_initial'),
        ('users', '0005_alter_user_documento_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='llamada',
            name='auditado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que auditó la llamada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llamadas_auditadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='llamada',
            name='estado_auditoria',
            field=models.ForeignKey(blank=True, help_text='Estado: auditada, no auditada', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='llamadas_estado_auditoria', to='users.tiposparametros'),
        ),
        migrations.AddField(
            model_name='llamada',
            name='fecha_auditoria',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se auditó la llamada', null=True, verbose_name='Fecha de Auditoría'),
        ),
        migrations.AddField(
            model_name='llamada',
            name='notas_auditoria',
            field=models.TextField(blank=True, help_text='Observaciones del auditor', verbose_name='Notas de Auditoría'),
        ),
    ]
