# Generated by Django 4.2.7 on 2025-10-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calls", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="llamada",
            name="fue_contestada",
            field=models.BooleanField(
                default=False,
                help_text="True si la llamada fue contestada (in-progress), False si solo timbró",
                verbose_name="Fue Contestada",
            ),
        ),
    ]
