# Generated by Django 5.2.7 on 2025-10-10 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_llamada_twilio_call_sid_llamada_twilio_recording_sid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llamada',
            name='estado_venta',
            field=models.CharField(choices=[('VENTA', 'Venta'), ('NO_VENTA', 'No Venta'), ('PENDIENTE', 'Pendiente')], default='NO_VENTA', max_length=20, verbose_name='Estado de venta'),
        ),
    ]
