# Generated by Django 5.2.7 on 2025-10-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_llamada_estado_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llamada',
            name='estado_venta',
            field=models.CharField(choices=[('VENTA', 'Venta'), ('NO_VENTA', 'No Venta'), ('PENDIENTE', 'Pendiente')], default='VENTA', max_length=20, verbose_name='Estado de venta'),
        ),
    ]
