# Generated by Django 5.2.7 on 2025-10-28 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_llamada_auditado_por_llamada_estado_auditoria_and_more'),
        ('users', '0005_alter_user_documento_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llamada',
            name='estado_auditoria',
            field=models.ForeignKey(blank=True, default=None, help_text='Estado: auditada, no auditada', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='llamadas_estado_auditoria', to='users.tiposparametros'),
        ),
    ]
