# Generated by Django 5.2.7 on 2025-10-30 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_llamada_fue_contestada'),
        ('calls', '0004_alter_llamada_estado_auditoria'),
    ]

    operations = [
    ]
