# Generated by Django 5.2.7 on 2025-10-12 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0004_alter_llamada_estado_venta'),
        ('campaigns', '0005_producto_alter_basedatoscargada_options_and_more'),
        ('users', '0004_centro_remove_equipo_supervisor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioVenta',
            fields=[
                ('formulario_id', models.AutoField(primary_key=True, serialize=False)),
                ('datos_formulario', models.JSONField(blank=True, null=True, verbose_name='Datos del Formulario')),
            ],
            options={
                'verbose_name': 'Formulario de Venta',
                'verbose_name_plural': 'Formularios de Ventas',
                'db_table': 'formulario_venta',
            },
        ),
        migrations.CreateModel(
            name='IteracionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intento', models.IntegerField(blank=True, null=True, verbose_name='ID Venta')),
            ],
            options={
                'verbose_name': 'Iteración de Cliente',
                'verbose_name_plural': 'Iteraciones de Clientes',
                'db_table': 'iteracion_cliente',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('venta_id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'venta',
            },
        ),
        migrations.RemoveField(
            model_name='llamada',
            name='campana',
        ),
        migrations.RemoveField(
            model_name='llamada',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='formulariollamada',
            name='agente',
        ),
        migrations.RemoveField(
            model_name='formulariollamada',
            name='llamada',
        ),
        migrations.RemoveIndex(
            model_name='llamada',
            name='calls_llama_cliente_4f9b18_idx',
        ),
        migrations.RemoveIndex(
            model_name='llamada',
            name='calls_llama_estado__7be6c5_idx',
        ),
        migrations.RenameIndex(
            model_name='llamada',
            new_name='llamada_agente__10b35d_idx',
            old_name='calls_llama_agente__b50ec5_idx',
        ),
        migrations.RenameIndex(
            model_name='llamada',
            new_name='llamada_llamada_c73aee_idx',
            old_name='calls_llama_llamada_99841c_idx',
        ),
        migrations.RenameIndex(
            model_name='llamada',
            new_name='llamada_telefon_29a689_idx',
            old_name='calls_llama_telefon_a3221e_idx',
        ),
        migrations.RemoveField(
            model_name='llamada',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='llamada',
            name='estado_llamada',
        ),
        migrations.RemoveField(
            model_name='llamada',
            name='intentos_redireccion',
        ),
        migrations.RemoveField(
            model_name='llamada',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='llamada',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='llamada',
            name='motivo_rechazo',
        ),
        migrations.RemoveField(
            model_name='llamada',
            name='notas',
        ),
        migrations.RemoveField(
            model_name='llamada',
            name='requiere_seguimiento',
        ),
        migrations.RemoveField(
            model_name='llamada',
            name='tipo_llamada',
        ),
        migrations.RemoveField(
            model_name='llamada',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='llamada',
            name='campana_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llamadas', to='campaigns.campana'),
        ),
        migrations.AddField(
            model_name='llamada',
            name='cliente_id',
            field=models.ForeignKey(blank=True, db_column='cliente_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llamadas', to='campaigns.cliente'),
        ),
        migrations.AlterField(
            model_name='llamada',
            name='agente',
            field=models.ForeignKey(db_column='agente_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llamadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='llamada',
            name='estado_recibida',
            field=models.ForeignKey(db_column='estado_recibida_id', default=False, help_text='Si el agente aceptó la llamada', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.tiposparametros'),
        ),
        migrations.AlterField(
            model_name='llamada',
            name='estado_venta',
            field=models.ForeignKey(blank=True, db_column='estado_venta_id', help_text='Estado de la venta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estados_ventas', to='users.tiposparametros'),
        ),
        migrations.AlterField(
            model_name='llamada',
            name='twilio_call_sid',
            field=models.CharField(blank=True, help_text='ID único de la llamada en Twilio', max_length=100, null=True, unique=True, verbose_name='Twilio Call SID'),
        ),
        migrations.AlterModelTable(
            name='llamada',
            table='llamada',
        ),
        migrations.AddField(
            model_name='formularioventa',
            name='cliente_id',
            field=models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.CASCADE, related_name='formularios', to='campaigns.cliente'),
        ),
        migrations.AddField(
            model_name='formularioventa',
            name='llamada_id',
            field=models.ForeignKey(db_column='llamada_id', on_delete=django.db.models.deletion.CASCADE, related_name='formularios', to='calls.llamada'),
        ),
        migrations.AddField(
            model_name='iteracioncliente',
            name='campana_id',
            field=models.ForeignKey(blank=True, db_column='campana_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanas_iteraciones', to='campaigns.campana'),
        ),
        migrations.AddField(
            model_name='iteracioncliente',
            name='cliente_id',
            field=models.ForeignKey(blank=True, db_column='cliente_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_iteraciones', to='campaigns.cliente'),
        ),
        migrations.AddField(
            model_name='iteracioncliente',
            name='estado_interacion_llamada_id',
            field=models.ForeignKey(blank=True, db_column='estado_interacion_llamada_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iteraciones_estado', to='users.tiposparametros'),
        ),
        migrations.AddField(
            model_name='venta',
            name='campana_id',
            field=models.ForeignKey(db_column='campana_id', on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='campaigns.campana'),
        ),
        migrations.AddField(
            model_name='formularioventa',
            name='venta_id',
            field=models.ForeignKey(db_column='campana_id', on_delete=django.db.models.deletion.CASCADE, related_name='formularios', to='calls.venta'),
        ),
        migrations.DeleteModel(
            name='Campana',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='FormularioLlamada',
        ),
        migrations.AddIndex(
            model_name='iteracioncliente',
            index=models.Index(fields=['cliente_id', 'campana_id'], name='iteracion_c_cliente_79d6e7_idx'),
        ),
    ]
