# Generated by Django 5.2.7 on 2025-11-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0005_merge_20251030_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-venta_id'], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.AddField(
            model_name='llamada',
            name='twilio_child_call_sid',
            field=models.CharField(blank=True, help_text='ID del child call (cuando se usa Dial, como en llamadas automáticas)', max_length=100, verbose_name='Twilio Child Call SID'),
        ),
        migrations.AlterField(
            model_name='llamada',
            name='twilio_call_sid',
            field=models.CharField(blank=True, help_text='ID único de la llamada en Twilio (parent call)', max_length=100, verbose_name='Twilio Call SID'),
        ),
    ]
