# Generated by Django 5.2.7 on 2025-10-12 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0005_formularioventa_iteracioncliente_venta_and_more'),
        ('users', '0006_estadoagentedetalle_estado_agen_agente__34be79_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llamada',
            name='estado_recibida',
            field=models.ForeignKey(db_column='estado_recibida_id', default=None, help_text='Si el agente aceptó la llamada', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.tiposparametros'),
        ),
    ]
