# Generated by Django 5.2.7 on 2025-10-31 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0005_merge_20251029_2005'),
        ('calls', '0005_merge_20251030_1808'),
    ]

    operations = [
    ]
