# Generated by Django 5.2.7 on 2025-10-31 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0006_merge_20251031_1751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-venta_id'], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
    ]
