# Generated by Django 5.2.7 on 2025-11-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0006_alter_venta_options_llamada_twilio_child_call_sid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llamada',
            name='twilio_child_call_sid',
            field=models.CharField(blank=True, help_text='ID del child call (cuando se usa Dial, como en llamadas automáticas)', max_length=100, null=True, verbose_name='Twilio Child Call SID'),
        ),
    ]
