# Generated by Django 5.2.7 on 2025-11-05 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0007_alter_llamada_twilio_child_call_sid'),
        ('calls', '0007_alter_venta_options'),
    ]

    operations = [
    ]
