# Generated by Django 5.2.7 on 2025-11-11 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0008_merge_20251105_1635'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteLlamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(help_text='Descripción detallada del problema (mínimo 10, máximo 500 caracteres)', verbose_name='Descripción del Reporte')),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó el reporte', verbose_name='Fecha del Reporte')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('llamada', models.ForeignKey(help_text='Llamada reportada', on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='calls.llamada')),
                ('reportado_por', models.ForeignKey(help_text='Usuario de BackOffice que creó el reporte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de Llamada',
                'verbose_name_plural': 'Reportes de Llamadas',
                'db_table': 'reporte_llamada',
                'ordering': ['-fecha_reporte'],
                'indexes': [models.Index(fields=['llamada', '-fecha_reporte'], name='reporte_lla_llamada_e46001_idx'), models.Index(fields=['reportado_por', '-fecha_reporte'], name='reporte_lla_reporta_5a4ecd_idx')],
            },
        ),
    ]
