# Generated by Django 5.2.7 on 2025-11-20 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0009_reportellamada'),
        ('campaigns', '0007_campana_comision_porcentaje'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('comision_id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Monto en pesos de la comisión', max_digits=10, verbose_name='Cantidad (Monto de Comisión)')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('agente', models.ForeignKey(help_text='Agente que realizó la venta', on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(blank=True, help_text='Producto vendido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comisiones', to='campaigns.producto')),
                ('venta', models.OneToOneField(help_text='Venta asociada a esta comisión', on_delete=django.db.models.deletion.CASCADE, related_name='comision', to='calls.venta')),
            ],
            options={
                'verbose_name': 'Comisión',
                'verbose_name_plural': 'Comisiones',
                'db_table': 'comision',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['agente', '-fecha'], name='comision_agente__aa6748_idx')],
            },
        ),
    ]
